# Site settings
baseURL = "https://code4myself.github.io/"
theme = ["blank"]

languageCode = "en-us"
title = "Code For Myself Project"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
